language: node_js
node_js:
  - "12.14.1"

branches:
  only:
  - master
    
script:
  - npm install
  - ./node_modules/.bin/gitbook install
  - ./node_modules/.bin/gitbook build
  - ./node_modules/.bin/surge --domain http://gke-intro-courseware.surge.sh/ --project ./_book